# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\test\demo\examples\firewall\view\ui\show_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_showlog(object):
    def setupUi(self, showlog):
        showlog.setObjectName("showlog")
        showlog.resize(900, 700)
        self.listWidget = ListWidget(showlog)
        self.listWidget.setGeometry(QtCore.QRect(60, 60, 781, 581))
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()

        item = QtWidgets.QListWidgetItem()

        self.frame = CardWidget(showlog)
        self.frame.setGeometry(QtCore.QRect(40, 40, 821, 621))
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        # self.frame.setFrameShape(QtCore.Qt.QFrame::Shape::StyledPanel)
        # self.frame.setFrameShadow(QtCore.Qt.QFrame::Shadow::Raised)
        self.frame.setObjectName("frame")
        self.frame.raise_()
        self.listWidget.raise_()

        self.retranslateUi(showlog)
        QtCore.QMetaObject.connectSlotsByName(showlog)

    def retranslateUi(self, showlog):
        _translate = QtCore.QCoreApplication.translate
        showlog.setWindowTitle(_translate("showlog", "Form"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)


        self.listWidget.setSortingEnabled(__sortingEnabled)


from qfluentwidgets import CardWidget, ListWidget
