# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\HP\Desktop\test\demo\examples\firewall\view\ui\set_rules.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_setRules(object):
    def setupUi(self, setRules):
        setRules.setObjectName("setRules")
        setRules.resize(776, 592)
        self.pushButton = PushButton(setRules)
        self.pushButton.setGeometry(QtCore.QRect(40, 60, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = PushButton(setRules)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 60, 75, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = PushButton(setRules)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 60, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = PrimaryPushButton(setRules)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 60, 75, 24))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = PrimaryPushButton(setRules)
        self.pushButton_5.setGeometry(QtCore.QRect(480, 60, 75, 24))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(setRules)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(29, 39, 551, 71))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")

        self.retranslateUi(setRules)
        QtCore.QMetaObject.connectSlotsByName(setRules)

    def retranslateUi(self, setRules):
        _translate = QtCore.QCoreApplication.translate
        setRules.setWindowTitle(_translate("setRules", "Form"))
        self.pushButton.setText(_translate("setRules", "PushButton"))
        self.pushButton_2.setText(_translate("setRules", "PushButton"))
        self.pushButton_3.setText(_translate("setRules", "PushButton"))
        self.pushButton_4.setText(_translate("setRules", "PushButton"))
        self.pushButton_5.setText(_translate("setRules", "PushButton"))
from qfluentweights import PrimaryPushButton, PushButton
